// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHkET136PAIoSy-ky50xWgtz7QGuyPpdg',
    appId: '1:597070249746:web:14490c40058d5d80d2fdcb',
    messagingSenderId: '597070249746',
    projectId: 'newportfolio-78725',
    authDomain: 'newportfolio-78725.firebaseapp.com',
    storageBucket: 'newportfolio-78725.firebasestorage.app',
    measurementId: 'G-BXL38B0LEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBytNFTWdbAzm-Q8_Y16h4gPbqEWJpxkVY',
    appId: '1:597070249746:android:63d1f357143ecb2fd2fdcb',
    messagingSenderId: '597070249746',
    projectId: 'newportfolio-78725',
    storageBucket: 'newportfolio-78725.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuH4clLqZxGa7BmdqEOwWMWHdZHu3q4Uo',
    appId: '1:597070249746:ios:6980493be15cc9a1d2fdcb',
    messagingSenderId: '597070249746',
    projectId: 'newportfolio-78725',
    storageBucket: 'newportfolio-78725.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuH4clLqZxGa7BmdqEOwWMWHdZHu3q4Uo',
    appId: '1:597070249746:ios:6980493be15cc9a1d2fdcb',
    messagingSenderId: '597070249746',
    projectId: 'newportfolio-78725',
    storageBucket: 'newportfolio-78725.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHkET136PAIoSy-ky50xWgtz7QGuyPpdg',
    appId: '1:597070249746:web:c3d060648d1360e7d2fdcb',
    messagingSenderId: '597070249746',
    projectId: 'newportfolio-78725',
    authDomain: 'newportfolio-78725.firebaseapp.com',
    storageBucket: 'newportfolio-78725.firebasestorage.app',
    measurementId: 'G-281SRVSNZ0',
  );
}
